### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf


#### for reading the dataset

In [2]:
tf.__version__

'2.9.1'

## 1-Data preprocessing
#### importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data
###### Label the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


#### Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### split the dataset into two sets trainingset and test set 

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Now feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Building the ANN

#### Now initiating the ANN

In [12]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## 3 - Training the ANN
#### Compilation of the ANN

In [16]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training of the ANN in the TRAINING SET

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 45)

Epoch 1/45
250/250 [==============================] - 1s 3ms/step - loss: 0.5178 - accuracy: 0.7931
Epoch 2/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4545 - accuracy: 0.8025
Epoch 3/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4351 - accuracy: 0.8081
Epoch 4/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4281 - accuracy: 0.8127
Epoch 5/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4241 - accuracy: 0.8161
Epoch 6/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4222 - accuracy: 0.8189
Epoch 7/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4202 - accuracy: 0.8188
Epoch 8/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4187 - accuracy: 0.8202
Epoch 9/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4175 - accuracy: 0.8192
Epoch 10/45
250/250 [==============================] - 1s 3ms/step - loss: 0.4163 - accuracy: 0.8205

### Predicting the Test set results

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 3ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1512   83]
 [ 187  218]]


0.865